packages:
  - 'apps/*'
  - 'apps/web/*'
  - 'apps/mobile/*'
  - 'services/*'
  - 'services/gateway/*'
  - 'packages/*'

# Centralized version management for shared dependencies
# Usage: "react": "catalog:" in package.json
# Benefits: Single source of truth, prevents version drift
catalog:
  # React ecosystem
  react: ^19.2.3
  react-dom: ^19.2.3
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3

  # Build tools
  typescript: ^5.9.3
  vite: ^7.2.7
  tsup: ^8.5.1

  # Styling
  tailwindcss: ^4.1.18
  '@tailwindcss/vite': ^4.1.18

  # DnD Kit
  '@dnd-kit/core': ^6.3.1
  '@dnd-kit/sortable': ^10.0.0
  '@dnd-kit/utilities': ^3.2.2

  # Testing
  vitest: ^4.0.15
  '@testing-library/react': ^16.3.0
  '@testing-library/jest-dom': ^6.9.1
  '@playwright/test': ^1.57.0

  # Linting
  eslint: ^9.39.1
  '@typescript-eslint/eslint-plugin': ^8.49.0
  '@typescript-eslint/parser': ^8.49.0
