/**
 * Admin Enterprise Enums (Phase 2)
 * SCIM 2.0 Enterprise User Schema + JML + NHI attributes
 */

// Employee Type (SCIM Enterprise)
export enum EmployeeType {
  REGULAR = 'REGULAR',
  CONTRACT = 'CONTRACT',
  INTERN = 'INTERN',
  PART_TIME = 'PART_TIME',
  VENDOR = 'VENDOR',
  CONTRACTOR = 'CONTRACTOR',
  CONSULTANT = 'CONSULTANT',
  AGENCY = 'AGENCY',
  TEMPORARY = 'TEMPORARY',
  SEASONAL = 'SEASONAL',
  SERVICE_ACCOUNT = 'SERVICE_ACCOUNT',
  SYSTEM = 'SYSTEM',
}

// Employment Status
export enum EmploymentStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  ON_LEAVE = 'ON_LEAVE',
  SUSPENDED = 'SUSPENDED',
  NOTICE_PERIOD = 'NOTICE_PERIOD',
  OFFBOARDING = 'OFFBOARDING',
  TERMINATED = 'TERMINATED',
  RETIRED = 'RETIRED',
  DECEASED = 'DECEASED',
}

// Account Lifecycle Status (SCIM)
export enum AccountLifecycleStatus {
  STAGED = 'STAGED',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  PROVISIONED = 'PROVISIONED',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  LOCKED = 'LOCKED',
  PASSWORD_EXPIRED = 'PASSWORD_EXPIRED',
  DEPROVISIONING = 'DEPROVISIONING',
  DEACTIVATED = 'DEACTIVATED',
  DELETED = 'DELETED',
}

// Job Family
export enum JobFamily {
  ENGINEERING = 'ENGINEERING',
  PRODUCT = 'PRODUCT',
  DESIGN = 'DESIGN',
  DATA = 'DATA',
  SALES = 'SALES',
  MARKETING = 'MARKETING',
  FINANCE = 'FINANCE',
  HR = 'HR',
  LEGAL = 'LEGAL',
  OPERATIONS = 'OPERATIONS',
  CUSTOMER_SUCCESS = 'CUSTOMER_SUCCESS',
  IT = 'IT',
  SECURITY = 'SECURITY',
  EXECUTIVE = 'EXECUTIVE',
  ADMINISTRATIVE = 'ADMINISTRATIVE',
  OTHER = 'OTHER',
}

// Identity Type (Human vs Non-Human Identity)
export enum IdentityType {
  HUMAN = 'HUMAN',
  SERVICE_ACCOUNT = 'SERVICE_ACCOUNT',
  BOT = 'BOT',
  API_CLIENT = 'API_CLIENT',
  MACHINE = 'MACHINE',
  WORKLOAD = 'WORKLOAD',
  SHARED_ACCOUNT = 'SHARED_ACCOUNT',
  EMERGENCY_ACCOUNT = 'EMERGENCY_ACCOUNT',
}

// Service Account Type (NHI)
export enum ServiceAccountType {
  BATCH_PROCESSING = 'BATCH_PROCESSING',
  API_INTEGRATION = 'API_INTEGRATION',
  ETL_PIPELINE = 'ETL_PIPELINE',
  MONITORING = 'MONITORING',
  BACKUP_RESTORE = 'BACKUP_RESTORE',
  CI_CD = 'CI_CD',
  AUTOMATION_RPA = 'AUTOMATION_RPA',
  SCHEDULED_TASK = 'SCHEDULED_TASK',
  MICROSERVICE = 'MICROSERVICE',
  EXTERNAL_VENDOR = 'EXTERNAL_VENDOR',
}

// NHI Credential Type
export enum NhiCredentialType {
  API_KEY = 'API_KEY',
  OAUTH_CLIENT = 'OAUTH_CLIENT',
  SERVICE_TOKEN = 'SERVICE_TOKEN',
  CERTIFICATE = 'CERTIFICATE',
  MANAGED_IDENTITY = 'MANAGED_IDENTITY',
  WORKLOAD_IDENTITY = 'WORKLOAD_IDENTITY',
}

// Remote Work Type
export enum RemoteWorkType {
  OFFICE = 'OFFICE',
  HYBRID = 'HYBRID',
  REMOTE_DOMESTIC = 'REMOTE_DOMESTIC',
  REMOTE_INTERNATIONAL = 'REMOTE_INTERNATIONAL',
  FIELD = 'FIELD',
  TRAVEL = 'TRAVEL',
}

// Security Clearance Level
export enum SecurityClearance {
  PUBLIC = 'PUBLIC',
  INTERNAL = 'INTERNAL',
  CONFIDENTIAL = 'CONFIDENTIAL',
  SECRET = 'SECRET',
  TOP_SECRET = 'TOP_SECRET',
}

// Data Access Level
export enum DataAccessLevel {
  NONE = 'NONE',
  BASIC = 'BASIC',
  TEAM = 'TEAM',
  DEPARTMENT = 'DEPARTMENT',
  SERVICE = 'SERVICE',
  PLATFORM = 'PLATFORM',
}

// Identity Verification Method
export enum VerificationMethod {
  DOCUMENT = 'DOCUMENT',
  BIOMETRIC = 'BIOMETRIC',
  VIDEO_CALL = 'VIDEO_CALL',
  IN_PERSON = 'IN_PERSON',
  DIGITAL_CERTIFICATE = 'DIGITAL_CERTIFICATE',
  KNOWLEDGE_BASED = 'KNOWLEDGE_BASED',
}

// Verification Level (KYC/AML)
export enum VerificationLevel {
  NONE = 'NONE',
  BASIC = 'BASIC',
  STANDARD = 'STANDARD',
  ENHANCED = 'ENHANCED',
  HIGH_ASSURANCE = 'HIGH_ASSURANCE',
}

// Probation Status
export enum ProbationStatus {
  NOT_APPLICABLE = 'NOT_APPLICABLE',
  IN_PROGRESS = 'IN_PROGRESS',
  PASSED = 'PASSED',
  EXTENDED = 'EXTENDED',
  FAILED = 'FAILED',
}

/**
 * HR Backend Enums (Phase 3)
 * Attendance & Leave Management
 */

// Attendance Status
export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  LATE = 'LATE',
  HALF_DAY = 'HALF_DAY',
  REMOTE = 'REMOTE',
  ON_LEAVE = 'ON_LEAVE',
  BUSINESS_TRIP = 'BUSINESS_TRIP',
  TRAINING = 'TRAINING',
  SICK = 'SICK',
  HOLIDAY = 'HOLIDAY',
}

// Work Type (where employee worked)
export enum WorkType {
  OFFICE = 'OFFICE',
  REMOTE = 'REMOTE',
  HYBRID = 'HYBRID',
  CLIENT_SITE = 'CLIENT_SITE',
  FIELD = 'FIELD',
  MOBILE = 'MOBILE',
}

// Leave Type
export enum LeaveType {
  ANNUAL = 'ANNUAL',
  SICK = 'SICK',
  PARENTAL = 'PARENTAL',
  MATERNITY = 'MATERNITY',
  PATERNITY = 'PATERNITY',
  UNPAID = 'UNPAID',
  COMPENSATORY = 'COMPENSATORY',
  STUDY = 'STUDY',
  BEREAVEMENT = 'BEREAVEMENT',
  MARRIAGE = 'MARRIAGE',
  MILITARY = 'MILITARY',
  SABBATICAL = 'SABBATICAL',
  SPECIAL = 'SPECIAL',
}

// Leave Status
export enum LeaveStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
  WITHDRAWN = 'WITHDRAWN',
}

// Work Schedule Type
export enum ScheduleType {
  STANDARD = 'STANDARD',
  SHIFT = 'SHIFT',
  FLEXIBLE = 'FLEXIBLE',
  COMPRESSED = 'COMPRESSED',
  ROTATING = 'ROTATING',
}
